### ISSUE TITLE
按照作者你的步骤，成功了，但是：sql_list没有值，是:[]，应该怎么配置，sql_list才有值？

### ISSUE THREAD

**Issue by hulang** [yzh52521/think-log-driver#1]
RT

**Comment by yuanzhihai** [comment]
// 大于0.05秒的sql将被记录
            'slow_sql_time'  => 0.5, 
            大于这个值才记录
            这个值设置小于sql 执行时间

**Comment by hulang** [comment]
@yzh52521 哈哈，没有仔细看。。。谢谢了。可以关闭了。
